# Generated by Django 2.2.5 on 2021-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_name',
        ),
        migrations.AddField(
            model_name='login',
            name='email_id',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
    ]
