# Generated by Django 2.2.5 on 2021-09-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20210926_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='username',
            field=models.TextField(default='example'),
        ),
    ]
